spring.application.name=backend
server.port=8090

# ===== PostgreSQL =====
spring.datasource.url=jdbc:postgresql://localhost:5432/harmoniq-DB
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ===== JWT =====
app.jwt.secret=MySuperSecureSecretKeyForJWTAuthentication123456
app.jwt.expiration=86400000


# ===== Redis =====
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=mypassword
spring.data.redis.ssl.enabled=false

logging.level.org.springframework.data.redis=DEBUG


# ===== File Upload =====
file.upload-dir=uploads/audioy


#
## ===============================
## APPLICATION
## ===============================
#spring.application.name=backend
#server.port=8080
#
#
## ===============================
## DATABASE (POSTGRESQL - DOCKER)
## ===============================
#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/harmoniq}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#
## ===============================
## JPA / HIBERNATE
## ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.open-in-view=false
#
#
## ===============================
## REDIS
## ===============================
#spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
#spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
#spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD:}
#spring.data.redis.ssl.enabled=false
#
#logging.level.org.springframework.data.redis=DEBUG
#
#
## ===============================
## JWT
## ===============================
#app.jwt.secret=MySuperSecureSecretKeyForJWTAuthentication123456
#app.jwt.expiration=86400000
#
#
## ===============================
## FILE UPLOAD
## ===============================
#file.upload-dir=uploads/audioy
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB.